### ISSUE TITLE
Integrate with the clipboard

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/plotgallery#1]
Electron has a nice API for clipboard integration: https://electronjs.org/docs/api/clipboard

We could make the usual shortcuts for "copy to clipboard" work, i.e. Ctrl+C would copy the currently active plot to the clipboard.

We could also add that option to the context menu that appears when one right clicks on a thumbnail.

**Comment by TonyLianLong** [comment]
I added the support with native event (https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event).

**Comment by davidanthoff** [comment]
Ok, I just tested it again (on Windows and Mac) and it all works :) So I think we can close this.

**Comment by juandarias** [comment]
@davidanthoff : is this enhancement already released with some version of the extension? I am on version 1.0.10 but I am not able to find this function.

**Comment by davidanthoff** [comment]
No, and we're probably going a different route for this now.
